name: Build WDA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-14
    steps:
    - name: WebDriverAgentをチェックアウト
      uses: actions/checkout@v4
      with:
        repository: appium/WebDriverAgent
    - name: Xcodeのバージョンを切り替え
      run: sudo xcode-select -s /Applications/Xcode_15.4.app
    - name: 依存関係のインストール
      run: brew install xcbeautify
    - name: ビルド
      run: |
        xcodebuild build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -destination "generic/platform=iOS" \
          -derivedDataPath ./DerivedData \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO
    - name: .devファイルに変換
      run: |
        cd DerivedData/Build/Products/Debug-iphoneos/
        zip -r WebDriverAgent.dev WebDriverAgentRunner-Runner.app/
        mv WebDriverAgent.dev ../../..
    - name: アーティファクトとしてアップロード
      uses: actions/upload-artifact@v4
      with:
        name: WebDriverAgent
        path: WebDriverAgent.dev
